[package]
name = "openlibx402-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "HTTP client library for the X402 payment protocol"
keywords = ["x402", "payment", "http", "client", "solana"]
categories = ["web-programming", "network-programming"]

[dependencies]
openlibx402-core = { path = "../openlibx402-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
solana-sdk.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
