[package]
name = "openlibx402-rocket"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Rocket web framework integration for X402 payment protocol"
keywords = ["x402", "payment", "rocket", "web", "middleware"]
categories = ["web-programming"]
readme = "README.md"

[dependencies]
openlibx402-core = "0.0.3"
rocket.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
uuid = { version = "1.11", features = ["v4"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
