[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "openlibx402-core"
version = "0.1.0"
description = "Core implementation of X402 payment protocol for autonomous AI agent payments"
authors = [
    {name = "OpenLibx402 Contributors", email = "hello@openlibx402.org"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.24.0",
    "solana>=0.30.0",
    "solders>=0.18.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/openlibx402/openlibx402"
Documentation = "https://docs.openlibx402.org"
Repository = "https://github.com/openlibx402/openlibx402"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]

[tool.ruff]
line-length = 88
target-version = "py38"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
